FROM nvidia/cuda:9.0-cudnn7-runtime-ubuntu16.04

RUN apt-get update && apt-get install -y \
    sudo \
    wget \
    software-properties-common

# install .Net Core SDK
# https://docs.microsoft.com/en-us/dotnet/core/install/linux-package-manager-ubuntu-1604

RUN wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
    && dpkg -i packages-microsoft-prod.deb \
    && rm -f packages-microsoft-prod.deb

RUN add-apt-repository universe && \
    apt-get update && apt-get install -y \
    apt-transport-https

RUN apt-get update && apt-get install -y \
    dotnet-sdk-3.1 \
    python3-pip \
    unzip \
    && rm -rf /var/lib/apt/lists/*

COPY ./requirements.txt ./

RUN pip install --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt