
FROM arm64v8/ubuntu:16.04

RUN apt-get update && apt-get install -y --no-install-recommends \
        sudo \
        automake \
        libtool-bin \
        sqlite \
        curl \
        libcurl4-openssl-dev \
        zlib1g-dev \
        git \
        build-essential \
        libssl-dev \
        libsqlite3-dev \
        wget