name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    paths:
      - 'arm/'
      - '.github/workflows/arm.yml'
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  DOCKER_USERNAME: drhippo

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [aarch64]
        version: [16.04, 16.04-gcc6, 18.04]
        include:
          - abi: armv7
            version: 16.04

    steps:
    - uses: actions/checkout@v2
    - name: Log CPU info
      run: cat /proc/cpuinfo
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: arm/${{ matrix.abi }}/${{ matrix.version }}/
        file: arm/${{ matrix.abi }}/${{ matrix.version }}/Dockerfile
        tags: drhippo/${{ matrix.abi }}:${{ matrix.version }}
        push: ${{ github.ref == 'refs/heads/master' }}
        cache-from: type=local,src=/tmp/${{ matrix.version }}/.buildx-cache
        cache-to: type=local,dest=/tmp/${{ matrix.version }}/.buildx-cache
