name: Docker Image CI

on:
  push:
    paths: 
      - 'aarch64/'
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  DOCKER_USERNAME: drhippo

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: arm/aarch64/16.04/
        file: arm/aarch64/16.04/Dockerfile
        tags: drhippo/aarch:16.04
        push: true
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache



